### ISSUE TITLE
Feature Request: A way to disable k8s

### ISSUE THREAD

**Issue by hyperbolic2346** [juju-solutions/microk8s#12]
It would be nice to not have to re-install microk8s when you want to use it or leave it running all the time. A way to just disable it all with a single switch would be nice even if it was just a single systemd thing.

**Comment by marcoceppi** [comment]
Apparently there's a snap disable and snap enable which we should test and leverage

**Comment by marcoceppi** [comment]
I tested this today

```
sudo snap install microk8s --classic --beta
microk8s.enable dns dashboard
sleep 30
sudo snap disable microk8s
sudo snap enable microk8s
sleep 30
microk8s.kubectl get all -n kubeflow
```

We should purse this as the option to "disable" going forward
