### ISSUE TITLE
Missing ingress rule for http://www.microk8s.io/? -> :'(

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/microk8s#18]
Hi @marcoceppi, 

I think you have a missing ingress rule or misconfigured LB for the .io site, the following work fine: 

- https://microk8s.io/
- http://microk8s.io/

But the following do not work: 

- https://www.microk8s.io/
- http://www.microk8s.io/

Good work here @ktsakalozos, better than Conjure-up for single node installs. My only other suggestion would be to add instructions for expanding the cluster through discoverer/CDK to get production support. 

Cheers

**Comment by marcoceppi** [comment]
This has been fixed, please allow up to 24 hours for those who visited that URL prior to the change for it to take affect.

**Comment by CalvinHartwell** [comment]
Cheers
