### ISSUE TITLE
Referenced `microk8s.config` command doesn't exist

### ISSUE THREAD

**Issue by AdamIsrael** [juju-solutions/microk8s#54]
As mentioned in the README, `microk8s.config > $HOME/.kube/config` fails because `microk8s.config` isn't installed by the snap.

**Comment by kwmonroe** [comment]
@AdamIsrael the `microk8s.config` command came in with https://github.com/juju-solutions/microk8s/pull/19.  It's currently available in edge:
```
$ snap info microk8s | grep -B1 -E 'microk8s.config|installed'
commands:
  - microk8s.config
--
  edge:      v1.10.4 (93) 174MB classic
installed:   v1.10.4 (93) 174MB classic
```

If moving to `edge` isn't an option, you should be able to get the same info with `microk8s.kubectl config view --raw`.

**Comment by ktsakalozos** [comment]
@AdamIsrael it is strongly recommended to deploy to microk8s in edge. There a lot of fixes and features there. there will be a release to beta soon but I do not know when.

**Comment by marcoceppi** [comment]
What is stopping a beta release?

**Comment by ktsakalozos** [comment]
@marcoceppi I would like to make the release through our CI and by integrating the test https://github.com/juju-solutions/microk8s/pull/51 . It is a good first step to not breaking the deployments of our users.

**Comment by AdamIsrael** [comment]
Switching to edge is fine for what I'm doing, maybe even preferable.

Thanks all!
