### ISSUE TITLE
microk8s.config > $HOME/.kube/config, .config doesn't seem to exist

### ISSUE THREAD

**Issue by jwhitlark** [juju-solutions/microk8s#56]
Did you perhaps mean:

microk8s.kubectl config view > $HOME/.kube/config

Or is this something from the bleeding edge?

**Comment by tvansteenburgh** [comment]
Yeah, that would work too. But your guess was right, `microk8s.config` is only on --edge right now. You're the 2nd person to trip on this. We should update the readme to either say "you need edge", or just use the command you listed (which seems preferable tbh). Thanks for pointing this out.

**Comment by johnsca** [comment]
The purpose of the `microk8s.config` wrapper is mainly to use the host IP as the endpoint address rather than the loopback address.  The commands use loopback internally, but it's more likely that you'd want the host IP if you're using the config externally.

**Comment by johnsca** [comment]
Oh, it also changes the default for `--raw` to `true` rather than `false` which is necessary for using the config with an external kubectl.  The actual equivalent command is:

```bash
DEFAULT_INTERFACE="$(netstat -rn | grep '^0.0.0.0' | awk '{print $NF}')"
IP_ADDR="$(ifconfig "$DEFAULT_INTERFACE" | grep 'inet ' | "$SNAP/usr/bin/gawk" '{print $2}' | "$SNAP/bin/sed" -e 's/addr://')"
microk8s.config view --raw | "$SNAP/bin/sed" -e "s/127.0.0.1/$IP_ADDR/"
```

**Comment by jwhitlark** [comment]
Ah, that explains a lot.  Ok, I'll switch to edge.  Thanks!
