### ISSUE TITLE
Can't 'sudo snap remove microk8s'

### ISSUE THREAD

**Issue by carmine** [juju-solutions/microk8s#58]
Installed microk8s
Installed kubeflow.
Rather than remove kubeflow, I decided to just remove microk8s. But, it errors:

```
$ sudo snap remove microk8s
error: cannot perform the following tasks:
- Stop snap "microk8s" services ([start snap.microk8s.daemon-apiserver.service snap.microk8s.daemon-docker.service snap.microk8s.daemon-etcd.service snap.microk8s.daemon-proxy.service snap.microk8s.daemon-scheduler.service snap.microk8s.daemon-kubelet.service snap.microk8s.daemon-controller-manager.service] failed with exit status 5: Failed to start snap.microk8s.daemon-apiserver.service: Unit snap.microk8s.daemon-apiserver.service not found.
Failed to start snap.microk8s.daemon-docker.service: Unit snap.microk8s.daemon-docker.service not found.
Failed to start snap.microk8s.daemon-etcd.service: Unit snap.microk8s.daemon-etcd.service not found.
Failed to start snap.microk8s.daemon-proxy.service: Unit snap.microk8s.daemon-proxy.service not found.
Failed to start snap.microk8s.daemon-scheduler.service: Unit snap.microk8s.daemon-scheduler.service not found.
Failed to start snap.microk8s.daemon-kubelet.service: Unit snap.microk8s.daemon-kubelet.service not found.
Failed to start snap.microk8s.daemon-controller-manager.service: Unit snap.microk8s.daemon-controller-manager.service not found.
)
```

After that, still can't remove it.

```
$ snap list
Name              Version  Rev   Tracking  Developer         Notes
core              16-2.33  4830  stable    canonical         core
kubectl           1.10.3   405   stable    canonical         classic
microk8s          v1.10.3  55    beta      canonical         disabled,classic

```

**Comment by ktsakalozos** [comment]
Hi @carmine,

The failures in removing the snap are most probably because of mounted endpoints not cleaning up on time. If you do a `cat /proc/mounts | grep microk8s` you should be able to see what is still mounted. Then you can umount the endpoints manually and try to re-remove the snap. 

This has been addressed in the snap in edge. We will be doing a release to beta soon in the meantime could you use the edge channel? `sudo snap install microk8s --classic --edge`
 
Thanks.

**Comment by arno01** [comment]
@carmine make sure you run ``microk8s.reset`` before ``snap remove microk8s``
https://github.com/juju-solutions/microk8s/blob/608e/README.md#removing-microk8s

**Comment by ktsakalozos** [comment]
@carmine the recent release that recently hit beta has addressed a number of cases where  microk8s  is not removed cleanly. Based on our private discussions I gather you are not seeing this issue anymore. 

I am closing this for now, please reopen if you see this again. Thank you for reporting the issue.

**Comment by tsoarescruz** [comment]
For me, this command 'sudo snap remove microk8s' worked

**Comment by yasir2000** [comment]
Am unable to remove microk8s cleanly, am getting :  
> microk8s.reset
Failed to query the cluster nodes.

Then 

> snap remove microk8s
error: system does not fully support snapd: cannot mount squashfs image using "squashfs": exec:
       "mount": executable file not found in $PATH
