### ISSUE TITLE
connection to server refused

### ISSUE THREAD

**Issue by jbottum** [juju-solutions/microk8s#61]
josh@ubuntu:~$ snap install microk8s --classic --beta
snap "microk8s" is already installed, see 'snap help refresh'

josh@ubuntu:~$ microk8s.kubetl get all
microk8s.kubetl: command not found

josh@ubuntu:~$ microk8s.enable dns dashboard
Applying DNS manifest
The connection to the server 127.0.0.1:8080 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:8080 was refused - did you specify the right host or port?

josh@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

**Comment by ktsakalozos** [comment]
Hi @jbottum,

Thank you for reporting this.

> josh@ubuntu:~$ microk8s.kubetl get all
> microk8s.kubetl: command not found

This is a typo. It should be `microk8s.kubectl`. If you got this typo anywhere from the web please point us to the right direction and we will correct it.


> josh@ubuntu:~$ microk8s.enable dns dashboard
> Applying DNS manifest
> The connection to the server 127.0.0.1:8080 was refused - did you specify the right host or port?
> The connection to the server 127.0.0.1:8080 was refused - did you specify the right host or port?

We need to see why the apiserver failed to start. Can you make sure port 8080 on your machine is available (no other service is listening on it)? Can you show me the output of `sudo systemctl status snap.microk8s.daemon-apiserver.service` and `sudo journalctl -u snap.microk8s.daemon-apiserver.service`

Thank you.

**Comment by jbottum** [comment]
thanks.   do I need to run a command to make 8080 available ?   (sorry if its a basic question, i work in sales :)

here is some output

josh@ubuntu:~$ microk8s.kubectl get all
error: the server doesn't have a resource type "cronjobs"

josh@ubuntu:~$ sudo systemctl status snap.microk8s.daemon-apiserver.service
[sudo] password for josh: 
● snap.microk8s.daemon-apiserver.service - Service for snap application microk8s.daemon-apiser
   Loaded: loaded (/etc/systemd/system/snap.microk8s.daemon-apiserver.service; enabled; vendor
   Active: failed (Result: exit-code) since Mon 2018-06-18 23:38:44 CDT; 1 weeks 6 days ago
 Main PID: 18109 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavaila

josh@ubuntu:~$ sudo journalctl -u snap.microk8s.daemon-apiserver.service
-- Logs begin at Tue 2018-06-19 23:55:20 CDT, end at Mon 2018-07-02 10:30:13 CDT. --
-- No entries --
josh@ubuntu:~$

**Comment by tvansteenburgh** [comment]
@jbottum What's the output of `sudo netstat -tnlp | grep 8080`?

**Comment by jbottum** [comment]
nothing that i can see...I tried 3 times...

sudo netstat -tnlp | grep 8080
[sudo] password for josh: 
josh@ubuntu:~$ sudo netstat -tnlp | grep 8080
josh@ubuntu:~$ sudo netstat -tnlp | grep 8080
josh@ubuntu:~$

**Comment by jbottum** [comment]
ok, removing and reinstalling has fixed the installation issue, thank you

**Comment by Oipo** [comment]
@jbottum why did you close this? Reinstalling did not fix it, using an older version did not fix this?

**Comment by jbottum** [comment]
I don’t think that I did.  I think it auto closed.

**Comment by Oipo** [comment]
My apologies, I added this comment thinking it was my own issue. Please ignore what I said.
